# Generated by Django 4.1 on 2024-03-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="is_ordered",),
    ]
