# Generated by Django 4.1 on 2024-04-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_order_created_at_order_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_ordered",
            field=models.BooleanField(default=False),
        ),
    ]
