# Generated by Django 4.1 on 2024-04-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_order_is_ordered"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon", name="status", field=models.BooleanField(default=True),
        ),
    ]
